app:
  name: "web_app"
  mode: "dev"
  port: 8001

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "api"
  password: "6nv2lxTHDVuQUQN9"
  dbname: "api"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: "6nv2lxTHDVuQUQN9"
  dbname: 12
  pool_size: 100 #连接池大小

mongo:
  host: "127.0.0.1"
  port: 27017
  user: "admin"
  password: "6nv2lxTHDVuQUQN9"
  dbname: "api"
  auth_source: "admin"